name: pub-kickstart
permissions: 
  contents: write
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch: # manual publication

jobs:
  extract-readmes:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get repo name 
        id: repo 
        run: 
          echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_OUTPUT

      - name: Extract README & download images 
        run: | 
          mkdir -p extracted/docs/kickstart/${{ steps.repo.outputs.REPO_NAME }}/
          cp README.md extracted/docs/kickstart/${{ steps.repo.outputs.REPO_NAME }}/README.md

      - name: Get ai-on-openshift & copy files to target repo
        run: |
          git clone https://keklundrh:${GH_TOKEN}@github.com/keklundrh/ai-on-openshift.git ai-on-openshift
          
          
          # git clone https://github.com/keklundrh/ai-on-openshift ai-on-openshift
          
          mkdir -p ai-on-openshift/docs/kickstart/${{ steps.repo.outputs.REPO_NAME }}/
          cp extracted/docs/kickstart/${{ steps.repo.outputs.REPO_NAME }}/README.md ai-on-openshift/docs/kickstart/${{ steps.repo.outputs.REPO_NAME }}/README.md 
        env:
          GH_TOKEN: ${{ secrets.GH_ACTION_PUB_AI_KICKSTART }}


#      - name: Create PR in target repo
#        run: |
#          cd ai-on-openshift
#          branch="kickstart-sync-${{ github.run_id }}"
#
#          
#          git checkout -b $branch
#          git add .
#              
#          git config --global user.name "github-actions[bot]"
#          git config --global user.email "github-actions[bot]@users.noreply.github.com"
#          git commit -m "Add README and images from ${{ steps.repo.outputs.REPO_NAME }}"
#
#          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/keklundrh/ai-on-openshift.git
#          git push origin $branch
#          gh pr create \
#            --title "Add README from ${{ steps.repo.outputs.REPO_NAME }}" \
#            --body "This PR adds the README and associated images." \
#            --base main \
#            --head $branch
#        env:
#          GH_TOKEN: ${{ secrets.GH_ACTION_PUB_AI_KICKSTART }}

          
      - name: Create Pull Request to main 
        uses: peter-evans/create-pull-request@v7
        with:
          path: ai-on-openshift
          token: ${{ secrets.GH_ACTION_PUB_AI_KICKSTART }} # secrets.GITHUB_TOKEN
          title: "Update kickstart READMEs from rh-ai-kickstart" 
          body: "This PR contains updated README files extracted from all rh-ai-kickstart repositories" 
          base: main
          branch: update-rh-ai-kickstart-readmes
          commit-message: "Update kickstart READMES"

